source 'artsy'
source 'master'

target 'Artsy-UIButtons' do
    pod 'Artsy+OSSUIFonts'
    pod "Artsy-UIButtons", :path => "../"
end

target 'Tests', :exclusive => true do
    pod 'Artsy+OSSUIFonts'
    pod "Artsy-UIButtons", :path => "../"

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
