use_frameworks!
platform :ios, '8.0'

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Artsy-UIButtons' do
    pod 'Artsy+UIFonts'
    pod "Artsy-UIButtons", :path => "../"

    target 'Tests' do
      inherit! :search_paths
        pod 'Specta'
        pod 'Expecta'
        pod 'FBSnapshotTestCase', '~>2.1.0'
        pod 'Expecta+Snapshots'
    end
end

